// 婴幼儿辅食食谱参考数据
// 针对 6-24 月宝宝辅食添加
// 仅供参考，具体添加顺序请结合宝宝实际发育，新食材每次只加一种并观察 3 天

// 过敏原标签集合（allergens 为空数组 [] 表示低敏）
//   '蛋' | '鱼' | '虾' | '小麦' | '坚果' | '乳' | '大豆'

export interface BabyFoodRecipe {
  id: string;
  name: string;            // 食谱名
  category: string;        // 食材分类：米粉糊/蔬菜泥/水果泥/蛋类/肉禽鱼/粥面/手指食物
  minMonth: number;        // 建议起始月龄（满 X 个月可加）
  maxMonth?: number;       // 建议上限月龄（可选，如 12 表示 12 月前为主）
  allergens: string[];     // 过敏原标签，[] 表示低敏
  ingredients: string[];   // 食材清单
  steps: string[];         // 制作步骤
  nutritionTags: string[]; // 营养标签，如「高铁」
  tip?: string;            // 小贴士/注意事项
}

export const BABY_FOOD_RECIPES: BabyFoodRecipe[] = [
  // ─── 米粉糊（6 月+）───
  {
    id: 'rice_cereal_iron',
    name: '强化铁米粉',
    category: '米粉糊',
    minMonth: 6,
    allergens: [],
    ingredients: ['婴儿强化铁米粉 15g', '温水或母乳/配方奶 60ml'],
    steps: [
      '米粉倒入碗中，先加少量温水搅拌成糊状',
      '继续少量多次加水，搅拌至顺滑无颗粒',
      '初次添加调成稀糊状（酸奶状），随月龄逐渐增稠',
    ],
    nutritionTags: ['高铁', '易消化'],
    tip: '辅食首选。强化铁米粉能补足 6 月后母体储存铁的消耗，是第一口辅食的最佳选择。',
  },
  {
    id: 'rice_paste',
    name: '大米糊',
    category: '米粉糊',
    minMonth: 6,
    allergens: [],
    ingredients: ['大米 30g', '水 适量'],
    steps: [
      '大米洗净浸泡 1 小时',
      '连水倒入料理机打成细腻米浆',
      '米浆过筛后倒入奶锅，小火边煮边搅至浓稠',
    ],
    nutritionTags: ['易消化', '低敏'],
    tip: '自制米糊铁含量低，建议与强化铁米粉搭配或轮换。',
  },
  {
    id: 'millet_paste',
    name: '小米糊',
    category: '米粉糊',
    minMonth: 6,
    allergens: [],
    ingredients: ['小米 30g', '水 适量'],
    steps: [
      '小米淘洗干净，加水浸泡 30 分钟',
      '连同泡米水倒入料理机打成浆',
      '过筛后小火煮开，边煮边搅约 5 分钟至浓稠',
    ],
    nutritionTags: ['富含B族', '易消化'],
  },

  // ─── 蔬菜泥（6 月+）───
  {
    id: 'pumpkin_puree',
    name: '南瓜泥',
    category: '蔬菜泥',
    minMonth: 6,
    allergens: [],
    ingredients: ['南瓜 50g'],
    steps: [
      '南瓜去皮去籽，切薄片',
      '上锅大火蒸 15 分钟至软烂',
      '取出趁热压成细腻泥状，加少许温水调稀',
    ],
    nutritionTags: ['富含维A', '低敏'],
    tip: '南瓜天然微甜，宝宝接受度高，是早期蔬菜泥的热门选择。',
  },
  {
    id: 'carrot_puree',
    name: '胡萝卜泥',
    category: '蔬菜泥',
    minMonth: 6,
    allergens: [],
    ingredients: ['胡萝卜 50g', '植物油 2 滴'],
    steps: [
      '胡萝卜去皮切薄片',
      '蒸 15 分钟至软烂',
      '压成泥后拌入少许植物油（β-胡萝卜素为脂溶性）',
    ],
    nutritionTags: ['富含维A', '护眼'],
    tip: '加几滴油能帮助胡萝卜素吸收，但不要过量。',
  },
  {
    id: 'spinach_puree',
    name: '菠菜泥',
    category: '蔬菜泥',
    minMonth: 7,
    allergens: [],
    ingredients: ['菠菜叶 30g'],
    steps: [
      '菠菜只用嫩叶，洗净后沸水焯 30 秒（去草酸）',
      '捞出过凉水，挤干水分',
      '再次入沸水煮软，料理机打成泥',
    ],
    nutritionTags: ['富含铁', '富含叶酸'],
    tip: '菠菜含草酸较高，必须先焯水再烹调，以免影响钙吸收。',
  },
  {
    id: 'potato_puree',
    name: '土豆泥',
    category: '蔬菜泥',
    minMonth: 6,
    allergens: [],
    ingredients: ['土豆 60g', '母乳/配方奶 20ml'],
    steps: [
      '土豆去皮切丁',
      '蒸 20 分钟至筷子可轻松穿透',
      '压成泥，分次加入奶调成顺滑糊状',
    ],
    nutritionTags: ['富含碳水', '易饱腹'],
  },
  {
    id: 'broccoli_puree',
    name: '西兰花泥',
    category: '蔬菜泥',
    minMonth: 7,
    allergens: [],
    ingredients: ['西兰花 40g'],
    steps: [
      '西兰花掰小朵，淡盐水浸泡 10 分钟',
      '沸水焯 1 分钟捞出',
      '再蒸 8 分钟，打成细腻泥状',
    ],
    nutritionTags: ['富含维C', '富含钙'],
    tip: '西兰花易胀气，初次少量尝试，观察宝宝消化情况。',
  },
  {
    id: 'sweet_potato_puree',
    name: '红薯泥',
    category: '蔬菜泥',
    minMonth: 6,
    allergens: [],
    ingredients: ['红薯 60g'],
    steps: [
      '红薯去皮切薄片',
      '蒸 20 分钟至软烂',
      '压成泥，加少许温水调稀',
    ],
    nutritionTags: ['富含纤维', '防便秘'],
  },
  {
    id: 'purple_potato_puree',
    name: '紫薯泥',
    category: '蔬菜泥',
    minMonth: 7,
    allergens: [],
    ingredients: ['紫薯 50g'],
    steps: [
      '紫薯去皮切薄片',
      '蒸 20 分钟至软烂',
      '压成细腻泥状',
    ],
    nutritionTags: ['富含花青素', '抗氧化'],
  },
  {
    id: 'yam_puree',
    name: '山药泥',
    category: '蔬菜泥',
    minMonth: 7,
    allergens: [],
    ingredients: ['铁棍山药 60g'],
    steps: [
      '山药戴手套去皮（防痒），切小段',
      '蒸 20 分钟至软烂',
      '压成顺滑泥状',
    ],
    nutritionTags: ['健脾养胃', '易消化'],
    tip: '生山药汁液会刺激皮肤致痒，处理时务必戴手套。',
  },
  {
    id: 'tomato_puree',
    name: '番茄泥',
    category: '蔬菜泥',
    minMonth: 7,
    allergens: [],
    ingredients: ['熟透番茄 1 个（约 60g）'],
    steps: [
      '番茄顶部划十字，沸水烫 30 秒去皮',
      '去籽切块',
      '蒸 5 分钟或直接打泥（建议加热去酸）',
    ],
    nutritionTags: ['富含维C', '开胃'],
  },

  // ─── 水果泥（6 月+）───
  {
    id: 'apple_puree',
    name: '苹果泥',
    category: '水果泥',
    minMonth: 6,
    allergens: [],
    ingredients: ['苹果 1/2 个'],
    steps: [
      '苹果洗净去皮去核，切小块',
      '蒸 8 分钟至变软（更易消化）',
      '压成泥或料理机打泥',
    ],
    nutritionTags: ['富含果胶', '助消化'],
    tip: '蒸过的苹果泥更温和，对初次添加或腹泻期的宝宝尤其友好。',
  },
  {
    id: 'banana_puree',
    name: '香蕉泥',
    category: '水果泥',
    minMonth: 6,
    allergens: [],
    ingredients: ['熟透香蕉 1/3 根'],
    steps: [
      '选表皮带黑点的熟透香蕉',
      '切小段，用勺直接压成泥',
      '可加少许母乳调稀',
    ],
    nutritionTags: ['富含钾', '防便秘'],
    tip: '必须用熟透的香蕉，未熟香蕉含鞣酸反而会加重便秘。',
  },
  {
    id: 'pear_puree',
    name: '梨泥',
    category: '水果泥',
    minMonth: 6,
    allergens: [],
    ingredients: ['梨 1/2 个'],
    steps: [
      '梨去皮去核切小块',
      '蒸 10 分钟（更温和）',
      '压成泥状',
    ],
    nutritionTags: ['润肺', '富含水分'],
  },
  {
    id: 'avocado_puree',
    name: '牛油果泥',
    category: '水果泥',
    minMonth: 6,
    allergens: [],
    ingredients: ['熟透牛油果 1/4 个', '母乳/配方奶 10ml'],
    steps: [
      '牛油果对半切开去核，取果肉',
      '用勺压成泥',
      '加少许奶调稀（牛油果本身较干）',
    ],
    nutritionTags: ['富含好脂肪', '健脑'],
    tip: '牛油果氧化快，必须现做现吃，颜色变褐即不新鲜。',
  },
  {
    id: 'papaya_puree',
    name: '木瓜泥',
    category: '水果泥',
    minMonth: 7,
    allergens: [],
    ingredients: ['熟木瓜 50g'],
    steps: [
      '木瓜对半切开去籽',
      '取果肉，料理机打泥',
      '可直接食用，无需加热',
    ],
    nutritionTags: ['富含维A', '助消化'],
  },
  {
    id: 'blueberry_puree',
    name: '蓝莓泥',
    category: '水果泥',
    minMonth: 8,
    allergens: [],
    ingredients: ['蓝莓 20g'],
    steps: [
      '蓝莓用淡盐水浸泡 5 分钟',
      '清水冲洗干净',
      '料理机打成泥（皮籽可一并打碎）',
    ],
    nutritionTags: ['富含花青素', '抗氧化'],
    tip: '蓝莓皮富含花青素，但籽对低月龄宝宝略粗，建议过筛一次。',
  },

  // ─── 蛋类（8 月+）───
  {
    id: 'egg_yolk_puree',
    name: '蛋黄泥',
    category: '蛋类',
    minMonth: 8,
    allergens: ['蛋'],
    ingredients: ['鸡蛋 1 个', '母乳/温水 10ml'],
    steps: [
      '鸡蛋冷水下锅，水开后煮 8 分钟',
      '取出过凉水，剥壳取蛋黄',
      '用勺将蛋黄压碎，加少许奶/水调成糊',
    ],
    nutritionTags: ['高铁', '富含卵磷脂'],
    tip: '8 月起先加蛋黄。新引入鸡蛋时少量试敏（1/4 个起），观察 3 天无过敏再增量。',
  },
  {
    id: 'steamed_egg',
    name: '蛋羹',
    category: '蛋类',
    minMonth: 9,
    allergens: ['蛋'],
    ingredients: ['鸡蛋 1 个', '温水 60ml'],
    steps: [
      '鸡蛋打散，加入 1.5 倍温水搅匀',
      '过筛去泡沫，盖保鲜膜扎几个小孔',
      '水开后中小火蒸 10 分钟，关火焖 2 分钟',
    ],
    nutritionTags: ['高蛋白', '易消化'],
    tip: '水量和过筛是嫩滑的关键。务必中小火，大火蒸会出蜂窝。',
  },
  {
    id: 'whole_egg_custard',
    name: '蔬菜蒸全蛋',
    category: '蛋类',
    minMonth: 12,
    allergens: ['蛋'],
    ingredients: ['鸡蛋 1 个', '胡萝卜碎 1 勺', '温水 60ml'],
    steps: [
      '鸡蛋打散加 1.5 倍温水',
      '拌入焯过水的胡萝卜碎',
      '过筛后中小火蒸 10 分钟',
    ],
    nutritionTags: ['高蛋白', '富含维A'],
  },

  // ─── 肉禽鱼（7-8 月+）───
  {
    id: 'chicken_liver_puree',
    name: '鸡肝泥',
    category: '肉禽鱼',
    minMonth: 7,
    allergens: [],
    ingredients: ['鸡肝 30g', '姜片 2 片'],
    steps: [
      '鸡肝去筋膜切片，用清水浸泡 30 分钟去血水',
      '与姜片同煮 15 分钟至熟透',
      '捞出放入料理机，加少许煮肝水打成细腻泥',
    ],
    nutritionTags: ['补铁冠军', '富含维A'],
    tip: '动物肝脏补铁效果极佳，但每周不超过 1-2 次，避免维 A 过量。',
  },
  {
    id: 'pork_puree',
    name: '猪肉泥',
    category: '肉禽鱼',
    minMonth: 7,
    allergens: [],
    ingredients: ['瘦猪肉 30g', '姜片 1 片'],
    steps: [
      '猪肉去筋剁成蓉',
      '加姜片冷水下锅，煮 20 分钟至熟',
      '取出剁细或料理机打成泥',
    ],
    nutritionTags: ['富含蛋白', '富含B族'],
  },
  {
    id: 'chicken_puree',
    name: '鸡肉泥',
    category: '肉禽鱼',
    minMonth: 7,
    allergens: [],
    ingredients: ['鸡胸肉 30g', '姜片 1 片'],
    steps: [
      '鸡胸肉去筋膜切丁',
      '与姜片同煮 15 分钟',
      '料理机加少许煮鸡水打成细腻泥',
    ],
    nutritionTags: ['高蛋白', '低脂'],
  },
  {
    id: 'beef_puree',
    name: '牛肉泥',
    category: '肉禽鱼',
    minMonth: 8,
    allergens: [],
    ingredients: ['瘦牛肉 30g', '姜片 1 片'],
    steps: [
      '牛肉去筋剁成蓉',
      '加姜片冷水下锅焯出血沫',
      '换清水煮 30 分钟至软烂，打成泥',
    ],
    nutritionTags: ['高铁', '高锌'],
    tip: '牛肉铁和锌含量突出，是补铁的重要来源之一。',
  },
  {
    id: 'cod_puree',
    name: '鳕鱼泥',
    category: '肉禽鱼',
    minMonth: 8,
    allergens: ['鱼'],
    ingredients: ['鳕鱼 40g', '柠檬 1 片', '姜 1 片'],
    steps: [
      '鳕鱼解冻去刺去鱼皮，挤柠檬汁腌 10 分钟去腥',
      '与姜片同蒸 8 分钟',
      '仔细检查无刺后压成泥',
    ],
    nutritionTags: ['富含DHA', '高蛋白'],
    tip: '鱼类是高敏食物，初次少量试敏。务必反复检查无小刺。',
  },
  {
    id: 'salmon_puree',
    name: '三文鱼泥',
    category: '肉禽鱼',
    minMonth: 8,
    allergens: ['鱼'],
    ingredients: ['三文鱼 40g', '柠檬 1 片'],
    steps: [
      '三文鱼检查无刺，挤柠檬汁去腥',
      '上锅蒸 8 分钟',
      '压成泥或料理机打泥',
    ],
    nutritionTags: ['富含DHA', '富含好脂肪'],
  },
  {
    id: 'shrimp_ball',
    name: '虾滑',
    category: '肉禽鱼',
    minMonth: 12,
    allergens: ['虾'],
    ingredients: ['鲜虾仁 50g', '蛋清 1 个', '淀粉 5g'],
    steps: [
      '虾仁去虾线洗净',
      '与蛋清、淀粉一起放入料理机打成胶状',
      '挤成小丸子入沸水煮熟浮起即可',
    ],
    nutritionTags: ['高蛋白', '高钙'],
    tip: '虾是高敏食物，1 岁后引入仍需少量试敏。',
  },

  // ─── 粥面（8-10 月+）───
  {
    id: 'pork_greens_porridge',
    name: '瘦肉青菜粥',
    category: '粥面',
    minMonth: 9,
    allergens: [],
    ingredients: ['大米 30g', '瘦猪肉 20g', '青菜 2 棵'],
    steps: [
      '大米煮成软粥',
      '猪肉剁泥炒熟，青菜焯水切碎',
      '粥将好时拌入肉泥和青菜碎，再煮 2 分钟',
    ],
    nutritionTags: ['营养均衡', '易消化'],
  },
  {
    id: 'cod_veggie_noodle',
    name: '鳕鱼蔬菜面',
    category: '粥面',
    minMonth: 10,
    allergens: ['鱼', '小麦'],
    ingredients: ['宝宝短面条 20g', '鳕鱼 30g', '胡萝卜 20g'],
    steps: [
      '鳕鱼蒸熟去刺压碎，胡萝卜切碎',
      '面条掰短，与胡萝卜一起煮至软烂',
      '出锅前拌入鳕鱼泥',
    ],
    nutritionTags: ['富含DHA', '富含维A'],
  },
  {
    id: 'egg_yolk_pumpkin_porridge',
    name: '蛋黄南瓜粥',
    category: '粥面',
    minMonth: 9,
    allergens: ['蛋'],
    ingredients: ['大米 30g', '南瓜 30g', '熟蛋黄 1 个'],
    steps: [
      '大米与南瓜丁一起煮成软粥',
      '南瓜自然融化在粥中',
      '关火后拌入压碎的蛋黄',
    ],
    nutritionTags: ['富含维A', '高铁'],
  },
  {
    id: 'chicken_carrot_porridge',
    name: '鸡肉胡萝卜粥',
    category: '粥面',
    minMonth: 9,
    allergens: [],
    ingredients: ['大米 30g', '鸡胸肉 20g', '胡萝卜 20g'],
    steps: [
      '鸡肉剁泥，胡萝卜切碎',
      '大米煮粥，半程时加入鸡肉泥和胡萝卜碎',
      '小火煮至软烂',
    ],
    nutritionTags: ['高蛋白', '富含维A'],
  },
  {
    id: 'jujube_yam_porridge',
    name: '红枣山药粥',
    category: '粥面',
    minMonth: 10,
    allergens: [],
    ingredients: ['大米 30g', '山药 30g', '红枣 3 颗'],
    steps: [
      '山药去皮切丁，红枣去皮去核切碎',
      '与大米一起煮粥',
      '煮至山药软烂，红枣自然增甜',
    ],
    nutritionTags: ['健脾养胃', '补气'],
  },
  {
    id: 'tomato_beef_noodle',
    name: '番茄牛肉面',
    category: '粥面',
    minMonth: 10,
    allergens: ['小麦'],
    ingredients: ['宝宝面条 20g', '番茄 1/2 个', '牛肉 20g'],
    steps: [
      '番茄去皮切碎，牛肉剁泥',
      '少量油炒出番茄汁，加水煮开',
      '下面条和牛肉泥，煮至软烂',
    ],
    nutritionTags: ['开胃', '高铁'],
  },
  {
    id: 'shrimp_porridge',
    name: '鲜虾粥',
    category: '粥面',
    minMonth: 12,
    allergens: ['虾'],
    ingredients: ['大米 30g', '鲜虾仁 3 只', '青菜 1 棵'],
    steps: [
      '虾仁去虾线切小段',
      '大米煮粥，将好时加入虾仁煮 3 分钟',
      '关火前加入青菜碎',
    ],
    nutritionTags: ['高钙', '高蛋白'],
  },
  {
    id: 'tofu_veggie_porridge',
    name: '豆腐蔬菜粥',
    category: '粥面',
    minMonth: 10,
    allergens: ['大豆'],
    ingredients: ['大米 30g', '嫩豆腐 30g', '青菜 2 棵', '胡萝卜 15g'],
    steps: [
      '豆腐压碎，胡萝卜切碎，青菜焯水切碎',
      '大米煮粥，半程加入胡萝卜和豆腐',
      '出锅前加青菜碎',
    ],
    nutritionTags: ['富含植物蛋白', '高钙'],
    tip: '大豆是常见过敏原，初次少量试敏。',
  },
  {
    id: 'cheese_pasta',
    name: '奶酪通心粉',
    category: '粥面',
    minMonth: 12,
    allergens: ['小麦', '乳'],
    ingredients: ['通心粉 25g', '宝宝奶酪 1 片', '胡萝卜 15g'],
    steps: [
      '通心粉和胡萝卜碎煮至软烂',
      '捞出沥干',
      '趁热拌入奶酪片至融化',
    ],
    nutritionTags: ['高钙', '高蛋白'],
    tip: '1 岁后才可加少量奶酪/酸奶，但不能用成人含盐奶酪，须选低钠宝宝奶酪。',
  },

  // ─── 手指食物（10 月+）───
  {
    id: 'carrot_sticks',
    name: '蒸胡萝卜条',
    category: '手指食物',
    minMonth: 10,
    allergens: [],
    ingredients: ['胡萝卜 1 根'],
    steps: [
      '胡萝卜切成宝宝一手抓的长条',
      '蒸 10-12 分钟至软但仍成形（不要太烂）',
      '放至温热即可让宝宝抓握',
    ],
    nutritionTags: ['富含维A', '锻炼抓握'],
    tip: '蒸到「软但成形」最关键，太硬有噎住风险，太烂一抓就散。',
  },
  {
    id: 'egg_pancake',
    name: '鸡蛋饼',
    category: '手指食物',
    minMonth: 10,
    allergens: ['蛋', '小麦'],
    ingredients: ['鸡蛋 1 个', '面粉 2 勺', '水 适量'],
    steps: [
      '鸡蛋打散加面粉和水搅匀成稀面糊',
      '不粘锅小火，倒入面糊摊薄',
      '两面煎熟，切成小条',
    ],
    nutritionTags: ['高蛋白', '锻炼咀嚼'],
  },
  {
    id: 'meatball',
    name: '软肉丸',
    category: '手指食物',
    minMonth: 10,
    allergens: [],
    ingredients: ['猪肉 40g', '蛋清 1 个', '淀粉 5g'],
    steps: [
      '猪肉剁泥加蛋清淀粉顺一个方向搅打上劲',
      '挤成鹌鹑蛋大小的小丸子',
      '蒸 15 分钟或入沸水煮熟',
    ],
    nutritionTags: ['高蛋白', '锻炼咀嚼'],
    tip: '宝宝丸子和成人不同，必须做小（鹌鹑蛋大小），且质地柔软。',
  },
  {
    id: 'steamed_bun_cubes',
    name: '馒头块',
    category: '手指食物',
    minMonth: 10,
    allergens: ['小麦'],
    ingredients: ['无盐小馒头 1 个'],
    steps: [
      '馒头切成 1.5cm 见方的小块',
      '可稍微蒸热回软',
      '直接让宝宝抓握',
    ],
    nutritionTags: ['富含碳水', '锻炼抓握'],
  },
  {
    id: 'pumpkin_cake',
    name: '南瓜发糕',
    category: '手指食物',
    minMonth: 11,
    allergens: ['蛋', '小麦'],
    ingredients: ['南瓜泥 80g', '面粉 100g', '鸡蛋 1 个', '酵母 1g'],
    steps: [
      '南瓜泥放温加酵母鸡蛋面粉搅成稠糊',
      '发酵至 2 倍大',
      '上锅大火蒸 20 分钟，晾凉切块',
    ],
    nutritionTags: ['富含维A', '软糯易抓'],
  },
  {
    id: 'steamed_salmon_bites',
    name: '蒸三文鱼块',
    category: '手指食物',
    minMonth: 12,
    allergens: ['鱼'],
    ingredients: ['三文鱼 40g', '柠檬 1 片'],
    steps: [
      '三文鱼检查无刺，挤柠檬汁',
      '切成宝宝可一手抓的小块',
      '蒸 8 分钟至熟',
    ],
    nutritionTags: ['富含DHA', '锻炼咀嚼'],
  },
  {
    id: 'banana_oat_pancake',
    name: '香蕉燕麦饼',
    category: '手指食物',
    minMonth: 11,
    allergens: [],
    ingredients: ['熟香蕉 1/2 根', '即食燕麦片 30g', '鸡蛋 1 个'],
    steps: [
      '香蕉压成泥，加鸡蛋和燕麦片拌匀',
      '不粘锅小火，舀入面糊摊小饼',
      '两面煎至金黄',
    ],
    nutritionTags: ['富含好脂肪', '无添加糖'],
    tip: '燕麦非小麦，通常不算常见过敏原（注意查看产品是否含麸质污染）。',
  },
  {
    id: 'veggie_potato_pancake',
    name: '蔬菜土豆饼',
    category: '手指食物',
    minMonth: 11,
    allergens: ['蛋', '小麦'],
    ingredients: ['土豆 60g', '胡萝卜碎 10g', '青菜碎 10g', '面粉 1 勺', '鸡蛋 1/2 个'],
    steps: [
      '土豆蒸熟压泥',
      '拌入焯过水的胡萝卜碎、青菜碎、面粉和蛋液',
      '不粘锅小火煎成小饼，两面金黄',
    ],
    nutritionTags: ['营养均衡', '锻炼咀嚼'],
  },
];
