/**
 * 预设任务数据 - 按孕期阶段分类（唯一数据源）
 *
 * 2026-09 收敛：原双源（DB preset_tasks 表 + 本文件兜底）合并为代码单源，
 * DB 表由 021 迁移删除。合并时 SQL 侧的 custom 类型统一归入 daily（010 已消灭 custom）。
 *
 * 用途：
 * 1. 新用户首次登录种子注入（ensurePresetTasks.ts，按 (user_id, title) 去重）
 * 2. 任务页「可添加任务」推荐列表
 */

export type PregnancyStageOrPostpartum = 'preconception' | 'first' | 'second' | 'third' | 'postpartum';

export interface PresetTask {
  title: string;
  description: string;
  stage: PregnancyStageOrPostpartum;
  type: 'prenatal' | 'daily' | 'checkin';
  due_date?: string;
}

export const presetTasks: PresetTask[] = [
  // ========== preconception ==========
  { title: '口腔检查', description: '孕期牙齿问题处理受限，提前完成洗牙、补牙、拔智齿', stage: 'preconception', type: 'prenatal' },
  { title: '妇科检查', description: '检查子宫、卵巢健康，排除肌瘤、囊肿等问题', stage: 'preconception', type: 'prenatal' },
  { title: '孕前体检', description: '全面体检，包括血常规、尿常规、肝肾功能、血糖、血脂', stage: 'preconception', type: 'prenatal' },
  { title: '性激素六项', description: '评估卵巢功能和内分泌状态', stage: 'preconception', type: 'prenatal' },
  { title: '甲状腺功能检查', description: '甲状腺功能异常影响受孕和胎儿发育', stage: 'preconception', type: 'prenatal' },
  { title: '疫苗抗体检查', description: '确认风疹、乙肝、水痘抗体，不足则补种疫苗', stage: 'preconception', type: 'prenatal' },
  { title: '精液常规检查', description: '检查精子数量、活力、形态，确保男性生育能力', stage: 'preconception', type: 'prenatal' },
  { title: '遗传咨询', description: '如有家族遗传病史，提前进行遗传咨询和筛查', stage: 'preconception', type: 'prenatal' },
  { title: '体重管理', description: '将BMI调整至18.5-24的健康范围，过胖或过瘦均影响受孕', stage: 'preconception', type: 'daily' },
  { title: '作息调整', description: '保持规律作息，每晚7-8小时充足睡眠，避免熬夜', stage: 'preconception', type: 'daily' },
  { title: '停服禁忌药物', description: '咨询医生调整用药，停用孕期禁忌药物（如维A酸类）', stage: 'preconception', type: 'daily' },
  { title: '减少咖啡因', description: '每天咖啡因摄入不超过200mg（约1-2杯咖啡）', stage: 'preconception', type: 'daily' },
  { title: '均衡饮食', description: '增加蛋白质、蔬菜水果摄入，减少加工食品和外卖', stage: 'preconception', type: 'daily' },
  { title: '学习排卵期知识', description: '掌握排卵期计算方法，使用排卵试纸提高受孕率', stage: 'preconception', type: 'daily' },
  { title: '工作环境评估', description: '排查工作环境中的辐射、化学毒物、高温等有害因素', stage: 'preconception', type: 'daily' },
  { title: '心理建设', description: '夫妻沟通生育计划，调整心态，减轻备孕焦虑', stage: 'preconception', type: 'daily' },
  { title: '戒酒戒烟', description: '提前3个月戒酒戒烟，二手烟也要避免', stage: 'preconception', type: 'daily' },
  { title: '生育保险规划', description: '了解生育保险政策，确认报销流程和产假天数', stage: 'preconception', type: 'daily' },
  { title: '补充叶酸', description: '每天400-800微克叶酸，预防胎儿神经管畸形，双方同补', stage: 'preconception', type: 'daily' },
  { title: '规律运动', description: '每周150分钟中等强度运动，如快走、游泳、慢跑', stage: 'preconception', type: 'daily' },
  { title: '购置备孕用品', description: '准备基础体温计、排卵试纸、验孕棒等', stage: 'preconception', type: 'daily' },
  { title: '健康饮食打卡', description: '每天记录饮食，保证蛋白质和蔬果摄入', stage: 'preconception', type: 'checkin' },
  { title: '服用叶酸', description: '每天按时服用叶酸，夫妻同补效果更好', stage: 'preconception', type: 'checkin' },
  { title: '测量基础体温', description: '每天早晨醒来后测量基础体温，记录排卵周期', stage: 'preconception', type: 'checkin' },
  // ========== first ==========
  { title: 'ABO/Rh血型检查', description: '排查母婴血型不合导致的溶血风险', stage: 'first', type: 'prenatal' },
  { title: 'NT检查', description: '胎儿颈项透明层厚度检查，11-13周+6天最佳，早期筛查唐氏综合征', stage: 'first', type: 'prenatal' },
  { title: '传染病筛查', description: '乙肝、梅毒、艾滋病筛查，早发现早干预', stage: 'first', type: 'prenatal' },
  { title: '建档', description: '到社区医院或产检医院建立《母子健康手册》', stage: 'first', type: 'prenatal' },
  { title: '心电图', description: '评估心脏功能，排查心脏疾病', stage: 'first', type: 'prenatal' },
  { title: '早期唐氏筛查', description: '结合NT值+血清学指标，筛查21/18三体综合征', stage: 'first', type: 'prenatal' },
  { title: '甲状腺功能检查', description: 'TSH、FT3、FT4，甲减影响胎儿智力发育', stage: 'first', type: 'prenatal' },
  { title: '肝肾功能检查', description: '评估肝脏和肾脏代谢功能', stage: 'first', type: 'prenatal' },
  { title: '血常规+尿常规', description: '基础血液和尿液检查，排查贫血、尿路感染', stage: 'first', type: 'prenatal' },
  { title: '阴道分泌物检查', description: '排查阴道炎、衣原体等感染', stage: 'first', type: 'prenatal' },
  { title: '首次产检', description: '确认怀孕（血HCG+B超），建立孕期档案，查肝肾功能、血常规', stage: 'first', type: 'prenatal' },
  { title: '保持水分', description: '每天喝足1.5-2升水，缓解孕吐导致的脱水', stage: 'first', type: 'daily' },
  { title: '停用化妆品', description: '停用含维A酸、水杨酸的护肤品及染发剂、指甲油', stage: 'first', type: 'daily' },
  { title: '办理生育登记', description: '到社区/线上办理生育服务登记，后续报销产检费用', stage: 'first', type: 'daily' },
  { title: '学习孕早期知识', description: '了解1-12周胎儿发育过程和各阶段注意事项', stage: 'first', type: 'daily' },
  { title: '应对早孕反应', description: '少食多餐，吃苏打饼干缓解孕吐，避免油腻刺激食物', stage: 'first', type: 'daily' },
  { title: '清淡饮食', description: '以易消化的粥、面、蒸菜为主，保证基本营养摄入', stage: 'first', type: 'daily' },
  { title: '确定预产期', description: '根据B超核对预产期，规划后续产检时间表', stage: 'first', type: 'daily' },
  { title: '调整工作强度', description: '申请减少加班/重体力工作，避免有害工作环境', stage: 'first', type: 'daily' },
  { title: '购买孕期保险', description: '了解孕产险、新生儿险，越早买选择越多', stage: 'first', type: 'daily' },
  { title: '选择生产医院', description: '考察家附近的产科医院，了解床位、技术、距离等因素', stage: 'first', type: 'daily' },
  { title: '避免久坐久站', description: '每1小时起来活动5分钟，促进血液循环', stage: 'first', type: 'daily' },
  { title: '服用叶酸', description: '每天按时服用叶酸400-800微克，至少到孕12周', stage: 'first', type: 'checkin' },
  { title: '记录身体变化', description: '每天记录早孕反应、体重、身体变化', stage: 'first', type: 'checkin' },
  // ========== second ==========
  { title: '中期唐氏筛查', description: '15-20周血清学筛查，评估染色体异常风险', stage: 'second', type: 'prenatal' },
  { title: '大排畸B超', description: '20-24周系统超声检查，全面排查胎儿结构畸形', stage: 'second', type: 'prenatal', due_date: '2026-08-15' },
  { title: '大排畸B超（四维彩超）', description: '20-24周系统超声检查，全面排查胎儿结构畸形', stage: 'second', type: 'prenatal' },
  { title: '无创DNA检测', description: '12-22周抽血检测胎儿染色体，准确率99%以上', stage: 'second', type: 'prenatal' },
  { title: '无创DNA检测（NIPT）', description: '12-22周，抽血检测胎儿染色体，准确率99%以上', stage: 'second', type: 'prenatal' },
  { title: '糖耐量测试', description: '24-28周筛查妊娠期糖尿病，需要空腹8-12小时', stage: 'second', type: 'prenatal', due_date: '2026-09-01' },
  { title: '糖耐量测试（OGTT）', description: '24-28周筛查妊娠期糖尿病，需要空腹8-12小时', stage: 'second', type: 'prenatal' },
  { title: '羊膜穿刺', description: '16-22周，适用于高龄(35+)/高风险者，确诊染色体问题', stage: 'second', type: 'prenatal' },
  { title: '胎儿心脏彩超', description: '22-26周专项检查胎儿心脏结构和发育', stage: 'second', type: 'prenatal' },
  { title: '准备婴儿衣物', description: '根据季节准备新生儿和尚服、包被、口水巾', stage: 'second', type: 'daily' },
  { title: '参加孕妇课程', description: '参加医院/社区组织的孕教课，学习分娩和育儿知识', stage: 'second', type: 'daily' },
  { title: '均衡营养', description: '增加优质蛋白（鱼、蛋、奶），控制体重每周增长0.3-0.5kg', stage: 'second', type: 'daily' },
  { title: '妊娠纹护理', description: '每天涂抹妊娠纹护理油，保持腹部皮肤弹性', stage: 'second', type: 'daily' },
  { title: '孕期运动', description: '散步、孕妇瑜伽、游泳，每次30分钟，增强盆底肌', stage: 'second', type: 'daily' },
  { title: '学习分娩知识', description: '了解顺产/剖腹产的区别、产程、止痛方式', stage: 'second', type: 'daily' },
  { title: '布置婴儿房', description: '规划宝宝房间，选购婴儿床、衣柜、收纳柜', stage: 'second', type: 'daily' },
  { title: '开始海淘婴儿用品', description: '趁着有时间选购性价比高的婴儿用品、衣物', stage: 'second', type: 'daily' },
  { title: '感受胎动并记录', description: '孕18-20周后开始感受胎动，每天固定时间记录次数', stage: 'second', type: 'daily' },
  { title: '拍孕妇照', description: '24-28周肚子大小适中，是拍孕妇照的最佳时机', stage: 'second', type: 'daily' },
  { title: '控制体重', description: '孕中期每周增重0.3-0.5kg，保持合理增长速度', stage: 'second', type: 'daily' },
  { title: '穿着舒适', description: '穿宽松孕妇装、低跟防滑鞋，避免紧身衣和高跟鞋', stage: 'second', type: 'daily' },
  { title: '补充DHA', description: '每天200-300mg DHA，促进胎儿大脑和视网膜发育', stage: 'second', type: 'daily' },
  { title: '补钙', description: '每天摄入1000-1200mg钙，豆制品、绿叶菜、牛奶', stage: 'second', type: 'daily' },
  { title: '补铁', description: '每天摄入27mg铁，红肉、动物肝脏配合维C吸收', stage: 'second', type: 'daily' },
  { title: '选购婴儿大件', description: '选购婴儿床、推车、安全座椅、尿布台等大件用品', stage: 'second', type: 'daily' },
  { title: '孕期瑜伽', description: '每天进行孕期瑜伽练习，保持身体柔韧性', stage: 'second', type: 'checkin' },
  { title: '数胎动', description: '每天固定时间数胎动，了解宝宝活动规律', stage: 'second', type: 'checkin' },
  { title: '服用钙片', description: '每天按时补钙，预防抽筋和骨质流失', stage: 'second', type: 'checkin' },
  { title: '服用铁剂', description: '每天按时补铁，预防妊娠期贫血', stage: 'second', type: 'checkin' },
  { title: '涂抹妊娠纹油', description: '每天早晚涂抹腹部、乳房、大腿根部', stage: 'second', type: 'checkin' },
  // ========== third ==========
  { title: 'B族链球菌检测', description: '36-37周筛查，阳性需产时抗生素预防新生儿感染', stage: 'third', type: 'prenatal' },
  { title: '分娩方式评估', description: '37周后综合评估，确定顺产或剖腹产方案', stage: 'third', type: 'prenatal' },
  { title: '小排畸B超', description: '28-32周超声检查，确认胎儿发育情况、羊水量、胎盘位置', stage: 'third', type: 'prenatal' },
  { title: '心电图复查', description: '评估孕晚期心脏负荷，排查妊娠期心脏问题', stage: 'third', type: 'prenatal' },
  { title: '肝功能复查', description: '排查妊娠期肝内胆汁淤积症（ICP），影响胎儿安全', stage: 'third', type: 'prenatal' },
  { title: '胎位检查', description: '28-32周确定胎位，臀位/横位需考虑纠正措施', stage: 'third', type: 'prenatal' },
  { title: '胎心监护', description: '32周后每2周一次，36周后每周一次', stage: 'third', type: 'prenatal' },
  { title: '胎心监护（NST）', description: '32周后每2周一次，36周后每周一次，监测胎心和宫缩', stage: 'third', type: 'prenatal' },
  { title: '血常规复查', description: '确认无贫血，为分娩储备足够的血红蛋白', stage: 'third', type: 'prenatal' },
  { title: '骨盆测量', description: '评估骨盆大小和形态，判断是否适合顺产', stage: 'third', type: 'prenatal' },
  { title: '体重监测', description: '每周固定时间称重，孕晚期每周增重0.3-0.5kg', stage: 'third', type: 'daily' },
  { title: '准备月子餐清单', description: '根据产后恢复需求，规划第一周的月子餐', stage: 'third', type: 'daily' },
  { title: '准备育儿书籍', description: '准备育儿百科等参考书，随时查阅', stage: 'third', type: 'daily' },
  { title: '准爸爸产假申请', description: '向公司申请陪产假/护理假，了解相关政策', stage: 'third', type: 'daily' },
  { title: '凯格尔运动', description: '每天做盆底肌训练，增强分娩力量，预防产后漏尿', stage: 'third', type: 'daily' },
  { title: '制定产后恢复计划', description: '了解产后恢复时间线，产后修复运动规划', stage: 'third', type: 'daily' },
  { title: '办理入院手续', description: '提前到医院办理入院登记，准备好证件材料', stage: 'third', type: 'daily' },
  { title: '学习拉玛泽呼吸法', description: '学习分娩减痛呼吸法，陪产时能帮助妈妈缓解疼痛', stage: 'third', type: 'daily' },
  { title: '学习新生儿护理', description: '学习抱娃、换尿布、洗澡、拍嗝、脐带护理等技能', stage: 'third', type: 'daily' },
  { title: '安排月子服务', description: '确定月嫂/月子中心/父母照顾，签订服务合同', stage: 'third', type: 'daily' },
  { title: '安装婴儿安全座椅', description: '提前安装并调试婴儿安全座椅，出院必备', stage: 'third', type: 'daily' },
  { title: '少盐饮食', description: '减少盐分摄入，减轻水肿和妊娠高血压风险', stage: 'third', type: 'daily' },
  { title: '少量多餐', description: '子宫增大压迫胃部，改为少量多餐减轻不适', stage: 'third', type: 'daily' },
  { title: '左侧卧睡', description: '孕晚期建议左侧卧，改善胎盘血流，减轻水肿', stage: 'third', type: 'daily' },
  { title: '待产包准备', description: '打包入院物品：产褥垫、卫生巾、哺乳衣、吸管杯、纸尿裤、包被等', stage: 'third', type: 'daily' },
  { title: '散步', description: '每天散步30-60分钟，有助于顺产和胎儿入盆', stage: 'third', type: 'daily' },
  { title: '数胎动', description: '每天早中晚各数1小时胎动，3-5次/小时为正常', stage: 'third', type: 'daily' },
  { title: '整理家庭财务', description: '计算生育预算，安排好住院费和待产开支', stage: 'third', type: 'daily' },
  { title: '确定陪产人', description: '确定谁进产房陪产，提前了解医院陪产政策', stage: 'third', type: 'daily' },
  { title: '血糖监控', description: '血糖偏高者每日三餐后测量血糖，控制在标准范围内', stage: 'third', type: 'daily' },
  { title: '规划去医院的路线', description: '熟悉去医院的路线和交通情况，准备备用方案', stage: 'third', type: 'daily' },
  { title: '凯格尔运动打卡', description: '每天做3组凯格尔运动，每组10-15次', stage: 'third', type: 'checkin' },
  { title: '散步打卡', description: '每天散步30分钟以上，保持适度活动', stage: 'third', type: 'checkin' },
  { title: '数胎动打卡', description: '每天早中晚各数1小时并记录胎动次数', stage: 'third', type: 'checkin' },
  { title: '服用叶酸', description: '每天按时服用叶酸，部分指南建议持续到哺乳期', stage: 'third', type: 'checkin' },
  { title: '血糖测量', description: '每天三餐后测量血糖并记录', stage: 'third', type: 'checkin' },
  // ========== postpartum ==========
  { title: '产后42天复查（妈妈）', description: '产后42天到医院复查子宫恢复、伤口愈合、盆底功能', stage: 'postpartum', type: 'prenatal' },
  { title: '产后42天复查（宝宝）', description: '宝宝42天体检，评估生长发育和神经发育', stage: 'postpartum', type: 'prenatal' },
  { title: '产后腹部B超', description: '检查子宫复旧情况，确认恶露排净', stage: 'postpartum', type: 'prenatal' },
  { title: '卡介苗+乙肝疫苗', description: '出生后24小时内接种卡介苗和第一针乙肝疫苗', stage: 'postpartum', type: 'prenatal' },
  { title: '新生儿听力筛查', description: '出生后48-72小时进行听力初筛，未通过42天复查', stage: 'postpartum', type: 'prenatal' },
  { title: '新生儿疾病筛查', description: '出生后72小时足底采血，筛查苯丙酮尿症、甲减等遗传病', stage: 'postpartum', type: 'prenatal' },
  { title: '新生儿首次体检', description: '出生后24小时内进行首次体格检查', stage: 'postpartum', type: 'prenatal' },
  { title: '满月体检', description: '满月后全面体检，测量身高、体重、头围、听力复查', stage: 'postpartum', type: 'prenatal' },
  { title: '盆底肌功能评估', description: '产后42天后评估盆底肌恢复情况，必要时进行康复治疗', stage: 'postpartum', type: 'prenatal' },
  { title: '产后伤口护理', description: '顺产侧切/剖腹产伤口每日消毒护理，观察有无感染', stage: 'postpartum', type: 'daily' },
  { title: '产后修复运动', description: '从温和的腹式呼吸、凯格尔运动开始，逐步恢复', stage: 'postpartum', type: 'daily' },
  { title: '产后情绪管理', description: '关注情绪变化，预防产后抑郁，必要时寻求心理帮助', stage: 'postpartum', type: 'daily' },
  { title: '保证休息', description: '宝宝睡的时候妈妈也睡，尽量保证充足休息', stage: 'postpartum', type: 'daily' },
  { title: '办理出生医学证明', description: '医院/线上办理出生医学证明，后续上户口需要', stage: 'postpartum', type: 'daily' },
  { title: '办理新生儿医保', description: '出生后90天内办理，可追溯报销出生后的医疗费用', stage: 'postpartum', type: 'daily' },
  { title: '学习婴儿抚触', description: '学习婴儿抚触手法，促进宝宝神经发育和亲子关系', stage: 'postpartum', type: 'daily' },
  { title: '学习拍嗝和排气操', description: '掌握正确拍嗝手法和排气操，缓解宝宝肠胀气', stage: 'postpartum', type: 'daily' },
  { title: '安排满月酒', description: '如有需要，规划满月酒/百日宴的时间和筹备', stage: 'postpartum', type: 'daily' },
  { title: '恶露观察', description: '观察恶露颜色、量、气味变化，异常及时就医', stage: 'postpartum', type: 'daily' },
  { title: '整理产后康复计划', description: '制定科学的产后康复计划，包括盆底肌、腹直肌修复', stage: 'postpartum', type: 'daily' },
  { title: '母乳喂养', description: '按需哺乳，每2-3小时一次，注意正确衔乳姿势', stage: 'postpartum', type: 'daily' },
  { title: '申请生育津贴', description: '准备材料申请生育津贴和报销产检、住院费用', stage: 'postpartum', type: 'daily' },
  { title: '给宝宝上户口', description: '携带出生证明、父母身份证/户口本到派出所落户', stage: 'postpartum', type: 'daily' },
  { title: '记录喂养和排便', description: '记录每次吃奶时间、量和大小便次数，判断摄入是否充足', stage: 'postpartum', type: 'daily' },
  { title: '预约42天检查', description: '提前预约妈妈和宝宝42天体检', stage: 'postpartum', type: 'daily' },
  { title: '产后凯格尔运动', description: '每天坚持凯格尔运动，促进盆底肌恢复', stage: 'postpartum', type: 'checkin' },
  { title: '产后心情记录', description: '每天记录情绪变化，关注产后情绪健康', stage: 'postpartum', type: 'checkin' },
  { title: '记录宝宝作息', description: '每天记录宝宝吃奶、睡觉、换尿布的时间', stage: 'postpartum', type: 'checkin' },
];
